### ISSUE TITLE
Consider using ./pkg for libraries and making the project much more portable?

### ISSUE THREAD

**Issue by xplshn** [rockorager/vaxis#2]
Hi, have you considered creating a ./pkg directory and have libraries live there? It'd be great to be able to import certain parts of this project, such as Sixel, in others. For example, I am looking for a sixel library but I certainly don't want to add an entire TUI library for that.

**Comment by rockorager** [comment]
Sorry for the slow response on this.

Overall, I don't want to make separate packages for small parts of this project. I am willing to where it really makes sense, but I think that mostly has been done already (the parser, for example).

That said - vaxis uses [go-sixel](https://github.com/mattn/go-sixel), I would recommend using that as a sixel library. We do use an octreequant for faster quantization than the stock go-sixel library, but this is a single file package that can already be imported as a module (or copied into your project)
